on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: degen-tips-readme-action
        uses: dawsbot/degen-tips-readme-action@v1.1.0
        with:
          FARCASTER_USERNAME: "apoorvlathey"
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
